# Generated by Django 6.0.5 on 2026-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('police', 'Police'), ('rescue', 'Rescue Team'), ('hospital', 'Hospital'), ('utility', 'Utility Crew')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available_units', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
