# Generated by Django 5.2.7 on 2026-05-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('heatwave', 'Heatwave'), ('accident', 'Accident'), ('power_outage', 'Power Outage'), ('protest', 'Protest')], max_length=50)),
                ('severity', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('affected_population', models.IntegerField(default=0)),
                ('estimated_duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('investigating', 'Investigating')], default='investigating', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_type', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.5)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed')], default='available', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('social', 'Social Media'), ('weather', 'Weather'), ('traffic', 'Traffic'), ('sensor', 'Sensor'), ('field', 'Field Report')], max_length=50)),
                ('content', models.TextField()),
                ('credibility_score', models.FloatField(default=0.5)),
                ('urgency_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='incidents.incident')),
            ],
        ),
    ]
